[package]
name = "breakthrough"
version = "0.1.0"
authors = ["Lucas Pluvinage <lucas.pluvinage@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ansi_term = "0.12"
indicatif = "0.13"
rayon = "1.3.0"
unwrap = "1.2.1"
cursive = "0.14"
atomic-counter = "1.0.1"

[profile.release]
debug = true
