[game]
kind         = "Gym"
name         = "Breakout-v0"

[self_play]
batch_size   = 8
evaluators   = 2
generators   = 8

[training]
replay_buffer   = 5000
epoch           = 25000
batch           = 512
n_epoch         = 10000
save_replay_freq= 512
checkpoint_freq = 250000
weight_decay    = 1e-5

[mcts]
playouts        = 50

[mu]
reward_support  = 300
repr_shape      = [6, 6, 16]
unroll_steps    = 5
td_steps        = 10

[mu.puct]
c_base          = 19652.0
c_init          = 1.25
root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25
discount        = 0.997
value_support   = 300
